# Generated by Django 3.0.3 on 2020-02-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save', '0002_auto_20200211_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='completed_items',
        ),
        migrations.RemoveField(
            model_name='list',
            name='items',
        ),
        migrations.AddField(
            model_name='items',
            name='completed_items',
            field=models.TextField(null=True),
        ),
    ]
