# Generated by Django 3.0.3 on 2020-02-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save', '0005_auto_20200211_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='completed_items',
            field=models.TextField(blank=True, default=' '),
        ),
    ]
