# Generated by Django 3.0.3 on 2020-02-11 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('save', '0006_auto_20200211_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='completed_items',
            new_name='completed_item',
        ),
        migrations.RemoveField(
            model_name='items',
            name='items',
        ),
        migrations.AddField(
            model_name='items',
            name='item',
            field=models.TextField(default='add an item'),
        ),
        migrations.AlterField(
            model_name='items',
            name='lists',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='save.List'),
        ),
    ]
