# Generated by Django 3.0.3 on 2020-02-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save', '0007_auto_20200211_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item',
            field=models.CharField(max_length=200),
        ),
    ]
