# Generated by Django 3.0.3 on 2020-02-11 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('save', '0008_auto_20200211_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='lists',
            new_name='_list',
        ),
    ]
