# Generated by Django 3.0.3 on 2020-02-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save', '0009_auto_20200211_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
